version: "3.7"

networks: 
  app-tier:
    driver: bridge

services:
  server:
    container_name: node_server_container
    depends_on:
      - maria-db
    build:
      context: ./k-leasing-server
      dockerfile: Dockerfile
      args:
        buildno: 1
    environment:
      NODE_ENV: production
    networks: 
      - app-tier
    ports:
      - 3001:3001
    volumes:
      - ./k-leasing-server:/app
      - "/app/node_modules"
    command: npm start
  maria-db:
    container_name: maria_container
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: k_leasing_db
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: root
      # MARIADB_ALLOW_EMPTY_PASSWORD: ok
      MARIADB_ROOT_HOST: '%'
    ports:
      - 3307:3306
    expose: 
      - 3307
    networks: 
      - app-tier
    volumes:
      - ./db/vol_db:/var/lib/mysql
  client:
    build:
      context: ./k-leasing-fe
      dockerfile: Dockerfile
      args:
        buildno: 1
    container_name: client_container
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./k-leasing-fe:/app
      - "/app/node_modules"
    depends_on:
      - server
