export const SET_PERMISSION = "SET_PERMISSION"

export const MODAL_ACTIVE = "MODAL_ACTIVE"

export const NOTIFICATION = "NOTIFICATION"

export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
export const AUTH_LOGIN_PENDING = "AUTH_LOGIN_PENDING"
export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR"
export const AUTH_CONNECT_SERVER_SUCCESS = "AUTH_CONNECT_SERVER_SUCCESS"
export const AUTH_CONNECT_SERVER_PENDING = "AUTH_CONNECT_SERVER_PENDING"
export const AUTH_CONNECT_SERVER_ERROR = "AUTH_CONNECT_SERVER_ERROR"
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS"
export const AUTH_LOGOUT_PENDING = "AUTH_LOGOUT_PENDING"
export const AUTH_LOGOUT_ERROR = "AUTH_LOGOUT_ERROR"
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS"
export const AUTH_REGISTER_PENDING = "AUTH_REGISTER_PENDING"
export const AUTH_REGISTER_ERROR = "AUTH_REGISTER_ERROR"

export const USER_GET_INFO = "USER_GET_INFO"
export const USER_POST_INFO = "USER_POST_INFO"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_PENDING = "RESET_PASSWORD_PENDING"
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR"

export const INPUT_ACTIVE_DATA = "INPUT_ACTIVE_DATA"
export const INPUT_SET_DATA_SUCCESS = "INPUT_SET_DATA_SUCCESS"
export const INPUT_SET_DATA_PENDING = "INPUT_SET_DATA_PENDING"
export const INPUT_SET_DATA_ERROR = "INPUT_SET_DATA_ERROR"
export const INPUT_STATUS_DATA_SUCCESS = "INPUT_STATUS_DATA_SUCCESS"
export const INPUT_STATUS_DATA_PENDING = "INPUT_STATUS_DATA_PENDING"
export const INPUT_STATUS_DATA_ERROR = "INPUT_STATUS_DATA_ERROR"

export const MASTER_DATA_SUCCESS = "MASTER_DATA_SUCCESS"
export const MASTER_DATA_PENDING  = "MASTER_DATA_PENDING"
export const MASTER_DATA_ERROR = "MASTER_DATA_ERROR"

export const LOAN_DATA_SUCCESS = "LOAN_DATA_SUCCESS"
export const LOAN_DATA_PENDING  = "LOAN_DATA_PENDING"
export const LOAN_DATA_ERROR = "LOAN_DATA_ERROR"

export const DEALER_CONDITION_DATA_SUCCESS = "DEALER_CONDITION_DATA_SUCCESS"
export const DEALER_CONDITION_DATA_PENDING  = "DEALER_CONDITION_DATA_PENDING"
export const DEALER_CONDITION_DATA_ERROR = "DEALER_CONDITION_DATA_ERROR"

export const SEARCH_REPORT_DATA_SUCCESS = "SEARCH_REPORT_DATA_SUCCESS"
export const SEARCH_REPORT_DATA_PENDING  = "SEARCH_REPORT_DATA_PENDING"
export const SEARCH_REPORT_DATA_ERROR = "SEARCH_REPORT_DATA_ERROR"

export const REPORT_DATA_ALL_SUCCESS = "REPORT_DATA_ALL_SUCCESS"
export const REPORT_DATA_ALL_PENDING  = "REPORT_DATA_ALL_PENDING"
export const REPORT_DATA_ALL_ERROR = "REPORT_DATA_ALL_ERROR"

export const INVOICE_DATA_ALL_SUCCESS = "INVOICE_DATA_ALL_SUCCESS"
export const INVOICE_DATA_ALL_PENDING  = "INVOICE_DATA_ALL_PENDING"
export const INVOICE_DATA_ALL_ERROR = "INVOICE_DATA_ALL_ERROR"

export const DUEDATE_SET = "DUEDATE_SET"
export const DATE_SET = "DATE_SET"
